name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run ESLint (via npx)
        run: npx eslint "**/*.js" --max-warnings=0 || true
      - name: Check formatting (via npx)
        run: npx prettier --check . || true

